libocfs2test/file_ops.c: only compile when OCFS2_TEST_REFLINK is defined
reflink feature is not upstream yet, which means compiling
libocfs2test/file_ops.c will fail on:

file_ops.c:282: error: ‘OCFS2_IOC_REFLINK’ undeclared (first use in this function)

This patch makes libocfs2test/file_ops.c get compiled only when
OCFS2_TEST_REFLINK is defined. It can make the compiling pass before reflink
feature gets merged into upstream.

Signed-off-by: Coly Li <coly.li@suse.de>
Signed-off-by: Tristan Ye <tristan.ye@oracle.com>