remove union wait for wait3()
'union wait' is deprecated and will get compile error something like:
In function ‘sigchld_handler’:
error: storage size of ‘status’ isn’t known

So use 'int status' instead according to man wait3.

Signed-off-by: Joseph Qi <joseph.qi@linux.alibaba.com>